### ISSUE TITLE
XMLHttpRequest cannot load 

### ISSUE THREAD

**Issue by moqri** [googlecodelabs/webrtc-web#1]
Getting an error in Step 06 when hosting on server (Webfaction). Blank video from remote!

**Comment by nitobuendia** [comment]
Hello @moqri 

This API only works from https:// are you running your node server with https?
A potential workaround was provided in #48 

Would this be your issue too?

**Comment by samdutton** [comment]
Hi @moqri — apologies for the long delay in responding!

Hope you got this working in the end.

I'll close this now, but feel free to raise an issue if you're still experiencing problems.
