### ISSUE TITLE
other browser's support

### ISSUE THREAD

**Issue by peacemakr** [googlecodelabs/webrtc-web#10]
Does it support other browsers (FF etc)? If not, any ideas what changes might be needed or any other simple projects to use?

**Comment by aaronang** [comment]
@peacemakr Yes, WebRTC is supported by Firefox. On the [WebRTC website](https://webrtc.org/), you can find a list of supported browsers 😄 

@samdutton This issue can be closed in my opinion.

**Comment by samdutton** [comment]
Thanks @aaronang 

Hi @peacemakr — apologies for the delay in responding. Yes, WebRTC is supported by Firefox, Opera, Edge (Preview) and is now in WebKit (i.e. is planned for Safari). There are also native SDKs for Android, iOS and C++.

https://t.co/NV4CRMqK4Z
http://www.nojitter.com/post/240172318/microsoft-puts-new-edge-in-webrtc
