### ISSUE TITLE
getUserMedia() error   Error: TypeError

### ISSUE THREAD

**Issue by laaaaanceeee** [googlecodelabs/webrtc-web#18]
I'm stuck on step 5 and 6, I keep on having these typeErrors when accessing http://localhost:8080 on browser. Help would be greatly appreciated. :)

**Comment by moohyu** [comment]
yes .. chrome is error but firefox is ok.. You try firefox.   _

**Comment by laaaaanceeee** [comment]
Thank you, moohyu.
