### ISSUE TITLE
Video from webcam not showing

### ISSUE THREAD

**Issue by gurbaaj** [googlecodelabs/webrtc-web#20]
I am unable to see the video from my webcam...i tried index file for step01 folder bt still am unable to see a video ..

**Comment by nitobuendia** [comment]
@gurbaaj could you provide more details on how you are running this?
Are you running this from a server or localhost (this only works in https / localhost)? Any errors in console? What browser and operating system are you using?

**Comment by samdutton** [comment]
I'll close this now, but feel free to open an issue if you're still experiencing problems.
