### ISSUE TITLE
Step-04-- node index.js is not working 

### ISSUE THREAD

**Issue by ankitjain28may** [googlecodelabs/webrtc-web#21]

**Comment by datoml** [comment]
The problem in the index.js it the following.
In the socket.on('create or join', ... part there is this entry:
**var numClients = io.sockets.sockets.length;**

The correct syntax is:
**var numClients = io.sockets.clients.length;**

Hope that helps :).

**Comment by smurfxx** [comment]
I confirm it doesn't work, I have this error on console log:
Uncaught ReferenceError: scriptSource is not defined at skip.js:8
(after a users understands that needs to install node.js in their machine)

**Comment by mso122591** [comment]
Hi I am using windows. My friend was able to get node index.js working on linux. Is it different on windows?

**Comment by nitobuendia** [comment]
@ankitjain28may @datoml Could you provide the errors that you are getting? Thank you!

@smurfxx Could you provide the whole console messages? Thank you!

@mso122591 Could you try running npm install from the terminal on the same folder as index.js before running node index.js ? It seems this is missing a dependency which should be installed with the package.json. I think this could solve it. Thank you.

**Comment by datoml** [comment]
@nitobuendia sorry its too long ago and I haven't tried it since then.

**Comment by datoml** [comment]
@nitobuendia 
I tried with the latest files and get this error.

```
...webrtc-web\work\node_modules\node-static\lib\node-static.js:348
                      mime.lookup(files[0]) ||
                           ^

TypeError: mime.lookup is not a function
    at Server.respond (...webrtc-web\work\node_modules\node-static\lib\node-static.js:348:28)
    at ...webrtc-web\work\node_modules\node-static\lib\node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by nitobuendia** [comment]
@datoml Yes, that is "expected" as per #47 - a fix is on the way to update the node-static dependencies.

Was that the error you had? If yes, then, the two issues are duplicates of each other and we can work just with one :)

Thank you!

**Comment by datoml** [comment]
I can't confirm it with 100% what was the error back then but I think its a duplicate then :).

**Comment by samdutton** [comment]
Hi @ankitjain28may and @datoml — sorry it took us so long to get back to you about this.

I'll close this now as per @nitobuendia's comments, but feel free to open an issue if you're still experiencing problems.
