### ISSUE TITLE
No mention of Node.js requirement

### ISSUE THREAD

**Issue by joshuaptfan** [googlecodelabs/webrtc-web#23]
In step 7, corresponding to the "step-04" folder, you ask the user to run the commands "npm install" and "node index.js".

At no point in time do you provide a link for the user to install Node.js so that these commands will work. Nor is it mentioned in "Overview" under "What you'll need". It also takes some research to learn that NPM does not need to be installed separately because it is included with Node.js.

Secondly, after the "npm install" command, there is this sentence:

> You may get warnings, but if there are errors in red, **ask for help!**

The user is not in a classroom. There is no teacher to ask for help from.

**Comment by smurfxx** [comment]
In step 7 I think you must tell to install Node.js because this is a tutorial and specify to move the downloaded folders to the right place, for example in windows after you run npm install we have a "node_modules" folder and we must copy "socket.io-client" folder to work directory and rename that to "socket.io"

**Comment by samdutton** [comment]
Hi @joshuaptfan — apologies for the delay in responding.

> In step 7, corresponding to the "step-04" folder, you ask the user to run the commands "npm install" and "node index.js".
>
> At no point in time do you provide a link for the user to install Node.js so that these commands will work. Nor is it mentioned in "Overview" under "What you'll need". It also takes some research to learn that NPM does not need to be installed separately because it is included with Node.js.

Step 7 has a section at the top explaining how to install Node, with links, and explaining that this enables use to use NPM. Does this make sense?

![image](https://user-images.githubusercontent.com/205226/34161740-729aba46-e4c9-11e7-96b8-d61a4b3ef154.png)


>>You may get warnings, but if there are errors in red, ask for help!
>
> The user is not in a classroom. There is no teacher to ask for help from.

Good point — we built this codelab for use at Google events, where there are helpers, but many people will must use it directly from the site. I've updated the explanatory text and will republish soon.

**Comment by nitobuendia** [comment]
@samdutton I understand that this is fixed now :)

**Comment by samdutton** [comment]
@nitobuendia yup :). Closing.
