### ISSUE TITLE
socket.io newbies won't know how /socket.io/socket.io.js is served

### ISSUE THREAD

**Issue by PierreFritsch** [googlecodelabs/webrtc-web#28]
In the codelab step [7. Set up a signaling service to exchange messages](https://codelabs.developers.google.com/codelabs/webrtc-web/#6), the code for `index.html` contains the line:

    <script src="/socket.io/socket.io.js"></script>

Not all readers of this codelab might have the implicit knowledge that this works because the HTTP server is wrapped in Socket.IO, which intercepts requests for /socket.io/socket.io.js and sends the appropriate response automatically.

I advocate it would be helpful to add a hint about this.

**Comment by nitobuendia** [comment]
@samdutton #29 has been submitted. Hence, this can be closed.

**Comment by PierreFritsch** [comment]
Thanks for merging!
