### ISSUE TITLE
Step.9 Uncaught ReferenceError: io is not defined at main.js:45

### ISSUE THREAD

**Issue by vutuananhhd89** [googlecodelabs/webrtc-web#34]
![capture](https://user-images.githubusercontent.com/17673503/27768303-d4cb92dc-5f39-11e7-8ed6-69382eff7ddc.PNG)

I cannot snap and send photo,
Please help,

**Comment by kahwee** [comment]
You need to go to the directory `step-06` and do an `npm install`

**Comment by nitobuendia** [comment]
@vutuananhhd89 I am unable to reproduce. I feel that @kahwee could be right.

Could you confirm that:
1. This is still reproducible
2. You run npm install from terminal on the folder where index.js is before running node index.js

Thank you.

**Comment by samdutton** [comment]
Hi @vutuananhhd89 — apologies for the delay in responding to your question.

We haven't heard from you so I'll close this now, but let us know if you're still experiencing problems.

@kahwee — thanks for your help.

**Comment by aulamber** [comment]
Hello @samdutton,

Sorry for adding a comment to a closed issue, but I am having the same problem as @vutuananhhd89 in /step-04, see picture.

I did run "npm install" then "node index.js" in the /step-04 folder (no issue at that point).
The "io is not defined" error appears once I type a room name in the popup and click on "OK".

Do you know where this error comes from?
Thank you for your answer.

<img width="1123" alt="screen shot 2017-12-27 at 13 47 12" src="https://user-images.githubusercontent.com/6305268/34382191-88788b00-eb0d-11e7-8511-c8d1f656f504.png">

**Comment by nitobuendia** [comment]
@aulamber 

Hello Audrey,

The first error shows that the /socket.io/socket.io.js did not load.
As a result, io is not defined and fails.

Did you run "npm install" on the same directory of the same step? It seems that it did not install socket.io properly.

Could you send what you got on the file ["package-lock.json"](https://docs.npmjs.com/files/package-lock.json)? Also, could you send a screenshot of your terminal after running "npm install"?

Thank you,
Nito

**Comment by aulamber** [comment]
@nitobuendia 

Hello Nito,

Thank you for your answer. I used `npm install` in the wrong folder (/step4 and not /work). I copied-pasted the code in the correct folder and it worked. Sorry for the disturbance :)

**Comment by samdutton** [comment]
Hi @aulamber — thanks for the heads-up! 

@nitobuendia — we should add a note/reminder about where to run `npm install`.

**Comment by nitobuendia** [comment]
@samdutton 

`npm install` is mentioned only in step-04 (7).
`node index.js` is mentioned in steps: step-04 (7), step-05 (8) and step-06 (9).

An easy solution would be changing the section "Run the Node.js server" for "Install and Run the Node.js server" and remind about the installation there.

I'll send a Codelab change suggestion.

**Comment by samdutton** [comment]
@nitobuendia good call — thanks.

**Comment by zaid225** [comment]
this not working it gives refrence error io is not defined why we are using script file in html      <script src="../../socket.io/socket.io.js"></script> this file is not a present  ?

**Comment by zaid225** [comment]
![Screenshot (374)](https://user-images.githubusercontent.com/63539429/108333209-b6574c00-71f6-11eb-8069-d7ea7eecfe48.png)
this is the error
