### ISSUE TITLE
https and socketIO listen port

### ISSUE THREAD

**Issue by smurfxx** [googlecodelabs/webrtc-web#35]
I'm trying to setup a little public vps to test webrtc but I have this problem:
if I want to use the webcam I need to secure my hosting with SSL, so the webserver is running on port 443; now in index.js I tell to socketIO to listen on port 8080 but if I visit my site (https://mysite.com) index.js is not fired, if I visit my site with 8080 port (https://mysite.com:8080) I get an error 'ERR_SSL_VERSION_OR_CIPHER_MISMATCH' with chrome.

How can I solve this?

**Comment by smurfxx** [comment]
I solved disabling my httpd server and using the built-in web server of your script!

**Comment by nitobuendia** [comment]
@smurfxx Could you add more details on the steps for documentation? It could be helpful for other users. Also, does this mean we can mark this issue as resolved? Thank you.

**Comment by smurfxx** [comment]
You can sign this issue as "working as designed" because was a misunderstanding.

**Comment by nitobuendia** [comment]
Thanks for clarification!

**Comment by samdutton** [comment]
Thanks @smurfxx — and apologies for the delay in responding. Will close.
