### ISSUE TITLE
Issue with STUN and TURN in step5 (video streaming) 

### ISSUE THREAD

**Issue by ltrojanowski** [googlecodelabs/webrtc-web#37]
Hello,
It seems that there is an error in `var pcConfig`
```
var pcConfig = {
  'iceServers': [{
    'urls': 'stun:stun.l.google.com:19302' // this should be 'url': ... not 'urls'
  }]
};
```
later the `url` of `iceServers` are checked in the `requestTurn` function. What I do not understand is why is the stun server never used? The `requestTurn` function only checks for urls starting with 'turn:(...)'
`if (pcConfig.iceServers[i].url.substr(0, 5) === 'turn:') {`
Nowhere else are the urls even accessed. Is there code missing from the code sample? This would explain why I can't get the code to work outside of my local network.

**Comment by nanomosfet** [comment]
Yeah I had made that find too, but I think it is the other way around. The if statement should be
`if (pcConfig.iceServers[i].urls.substr(0, 5) === 'turn:') {` and not changing the pcConfig dictionary.

If you look at the [the documentation](https://www.w3.org/TR/webrtc/#configuration) they define the dictionary with urls.

**Comment by nitobuendia** [comment]
I am unable to reproduce the issue. However, I agree that the object pcConfig.iceServers[i].urls (at least [0] has urls as a property. Also, agreed that per documentation, urls seems the right parameter. Hence, updating if statement instead.

**Comment by moneytoo** [comment]
I had the same issue as OP - it didn't work outside the same network and STUN/TURN servers were never contacted. ``pcConfig`` is set but never used. It works once it's set as parameter in https://github.com/googlecodelabs/webrtc-web/blob/bcb772a0edae69131df72e6ef0eb28376c265a69/step-05/js/main.js#L149

**Comment by Archer-Thane** [comment]
@moneytoo I were opened the chrome://webrtc-internals/ and saw the iceServers:[] which does not make sense. 
Thanks
