### ISSUE TITLE
Steps cannot run without a server.

### ISSUE THREAD

**Issue by bfwg** [googlecodelabs/webrtc-web#4]
The `navigator.getUserMediaStep`'s callback won't trigger in step 1 to 3. 
This cause the video will not show.
After adding a node server, the affected step's video can show again.
Any thoughts?

**Comment by aaronang** [comment]
@bfwg Yes, this should happen for everyone. That's also the reason why lesson 3: "Get the sample code" explains step by step how to set up a local web server in Chrome.

**Comment by bfwg** [comment]
@aaronang oh man, it was nearly 8 month ago. I have learnt so much about webrtc and build an Angular2 Webrtc app. 

Thank you.
