### ISSUE TITLE
Streaming Video

### ISSUE THREAD

**Issue by jtrugman** [googlecodelabs/webrtc-web#41]
I am trying to modify the step 2 & step 6 code in order to make a basic video chat application. I was able to do the signaling, but can not stream the actual data. Has anyone done something similar like this or ran into a similar problem because there is no tutorial for an actual p2p video chat with socket.io

Thanks,
-Justin

**Comment by powerata23** [comment]
i have the same issue!! can u find the answer?

**Comment by samdutton** [comment]
Hi @jtrugman — sorry for the delay in responding. 

> p2p video chat with socket.io

I'm not sure I understand the question, but do you mean you want to implement video chat by transferring data via Socket.io? Just to be clear, Socket.io is only used for messaging: WebRTC is used to stream video data between clients (peers).

Did you manage to get it working in the end?

I'll close this now, but feel free to open an issue if you're still experiencing problems.
