### ISSUE TITLE
Step 7 socket.io and node.js

### ISSUE THREAD

**Issue by wmscom** [googlecodelabs/webrtc-web#42]
instead of downloading the socket file use this: <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>

concerning node.js -->    node index.js
it through several errors and doesn't work:
node index.js
c:\webrtc-web-master\work\node_modules\node-static\lib\node-static.js:348
                      mime.lookup(files[0]) ||
                           ^
TypeError: mime.lookup is not a function
    at Server.respond (c:\webrtc-web-master\work\node_modules\node-static\lib\node-static.js:348:28)
    at c:webrtc-web-master\work\node_modules\node-static\lib\node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:123:15)

calling http://localhost:8080/
returns:  net::ERR_CONNECITON_REFUSED

how do we get this working?

**Comment by kmvoorhees** [comment]
I am having the same issue with step 4. It appears to be an issue with the node-static module that was fixed just recently with version 0.7.10: https://github.com/cloudhead/node-static/issues/199
Changing the node-static version from 0.7.7 to 0.7.10 in package.json fixed the error for me.

**Comment by fabioshepherd** [comment]
I had the same problem. Thanks @kmvoorhees, I solved!

But now i have another problem, after I choose a name for the room the console show me this error repeatedly 

socket.io.js:2   POST http://127.0.0.1:8080/socket.io/?EIO=3&transport=polling&t=LwLyFLG 404 (Not Found)

Do anyone know how i can solve?

**Comment by yanzai3292** [comment]
@fabioshepherd I also faced the same problem... the error message "http://127.0.0.1:8080/socket.io/?EIO=3&transport=polling&t=LwPPZO2 404 (Not Found)"... Did anyone has any idea ?

**Comment by RedsAnDev** [comment]
Hi,
**just replace lookup with getType** and everything will works.

**Comment by yanzai3292** [comment]
@RedsAnDev  
Hi, may i know which "lookup" that you meant?

**Comment by RedsAnDev** [comment]
Instead `mime.lookup(files[0])` with `mime.getType(files[0])` wherever you needs.

**Comment by nitobuendia** [comment]
@wmscom 
Do not change the socket.io for a cdn, make sure you follow the codelab and run npm install and node index.js from terminal on the same server.

For the mime.lookup error, I have submitted some fixes on #47 which should solve it. Basically, it seems that upgrading node-static solves the issue.

Would that solve your issue?

**Comment by samdutton** [comment]
Hi @wmscom @kmvoorhees @fabioshepherd @yanzai3292 — apologies for the delay in responding.

As per @nitobuendia's comments, I'll close this — but feel free to raise an issue if there are still problems.
