### ISSUE TITLE
streaming

### ISSUE THREAD

**Issue by powerata23** [googlecodelabs/webrtc-web#46]
step 2, used like video chat between 2 pc? someone do it?

**Comment by nitobuendia** [comment]
Hello @powerata23, I am not sure if I am fully understanding your request. Could you explain it further? Thank you!

**Comment by nitobuendia** [comment]
After checking some other issues: it seems you are referring to the same as #41 ?

**Comment by samdutton** [comment]
Hi @powerata23 — thanks for filing the issue, and apologies for the delay in responding. 

I'll close this, but feel free to open again if you're still experiencing problems.
