### ISSUE TITLE
Step - 06 Render photo function is useless

### ISSUE THREAD

**Issue by SL-A-SH** [googlecodelabs/webrtc-web#49]
I was trying to save the image from the canvas to a database using canvas.toDataURL in the renderPhoto(data) and didn't succeeded in doing so.
I noticed that console.log() isn't working on that function so I decided to totally comment out renderPhoto(data) function and still the code is working fine. I can still see the image on the canvas without the renderPhoto(data) function.
I even cleared the cache. Didn't help.

**Comment by nitobuendia** [comment]
@SL-A-SH 
I am unable to reproduce this.

There is no console.log() in renderPhoto(data) {}.
When I add a console.log() with 'Rendering photo' it does logs successfully.
![screen shot 2017-11-28 at 21 33 17](https://user-images.githubusercontent.com/16522489/33322331-f562ce1a-d483-11e7-8350-d91e781c9251.png)

If I remove it, I get a console error.
![screen shot 2017-11-28 at 21 38 00](https://user-images.githubusercontent.com/16522489/33322471-7319dfce-d484-11e7-8d18-138d4949ee89.png)


Note that this function is not executed on the source, where you take the snap, but on the destination were you send the photo (this requires two channels).

Am I misunderstanding your issue? If yes, could you clarify the steps to reproduce?

Thank you!

**Comment by SL-A-SH** [comment]
Apparently I am an idiot. I was checking in the same tab. So I was able to view the image on the canvas on the same tab which is the sender. I did not check the receiver. I am getting `renderPhoto` is not defined on another tab (the receiver). So I am closing this issue.
 
Thank You

Now I just have to figure out how to save the image in a database.
