### ISSUE TITLE
Contributing to Documentation

### ISSUE THREAD

**Issue by ev1stensberg** [googlecodelabs/webrtc-web#58]
Is there any OSS repo where the documentation is served from, so that externals can help out?

**Comment by nitobuendia** [comment]
@ev1stensberg Hello Even,

Thanks a lot for your enthusiasm and willing to contribute.
Unfortunately, the text of the codelab is not on a repository.

However, if you want to make proposals: perhaps you can send them here and we can review them and try to incorporate if relevant for the team? Would that work?

Thank you,
Nito

// cc @samdutton

**Comment by samdutton** [comment]
Hi @ev1stensberg — as @nitobuendia says, many thanks for your offer to help out!

We maintain the codelab text content as a Google Doc. 

If you'd like to help, I suggest raising issues on this repo.

I'll close this issue, but feel free to open it again if you have more questions.

**Comment by ev1stensberg** [comment]
Hi @samdutton , could I send you a mail with suggested edit?

**Comment by pwa** [comment]
@ev1stensberg — sure, that'd be great. I'm samdutton@gmail.com.
