### ISSUE TITLE
Step-2 - Update of adapter.js required to work on Edge

### ISSUE THREAD

**Issue by superfaz** [googlecodelabs/webrtc-web#66]
**Summary**
In order to have the Step-2 working on Edge, I had to change the adapter.js library to the latest one.

**Issue details**
On Edge, the Start action works perfectly but the Call doesn't start the second stream.
No error visible on the console, but the pc2.onaddstream is never called by the app.

**Workaround**
By using the latest version of adapter.js: https://webrtc.github.io/adapter/adapter-latest.js (as of today: 6.1.1), the sample of the codelab - Step-2 was able to raise the "pc2.onaddstream" event and the code works perfectly since then.

**Comment by superfaz** [comment]
Just updated the description.
The issue is linked to the step-2 in the package, corresponding to the page 5 of the codelab :)

**Comment by nitobuendia** [comment]
The code on the repository currently refers to:
`<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>`

However, codelab still refers to:
`<script src="js/lib/adapter.js"></script>`

@superfaz I understand you mean changing the text/code on the actual codelab and not so much the code on this repository. Is that correct?

**Comment by superfaz** [comment]
Correct!

**Comment by nitobuendia** [comment]
@superfaz Thanks for reporting :)
@samdutton Sent changes for review on the codelab "text". Once applied, kindly mark this as fixed.

**Comment by samdutton** [comment]
I've published the updates to the codelab text.

Thanks @superfaz and @nitobuendia!
