### ISSUE TITLE
step-06 is not working

### ISSUE THREAD

**Issue by Im10Anish** [googlecodelabs/webrtc-web#67]
The app works fine till step-05 but after include step-06 into my code then it shows getUserMedia() error: ReferenceError. When it not working from work directory then I tried directly from the step-06 directory but still same error shows. Can you please look into that.

**Comment by nitobuendia** [comment]
@Im10Anish Sorry to hear the issues and thanks a lot for reporting.

Could you paste here the whole content of your console logs? That'd help to troubleshoot or identify the issue.

Thank you so much for reporting!

**Comment by bedus-creation** [comment]
Yes Step-6 is not working, It says =>
 **getUserMedia() error: ReferenceError**

**Comment by nitobuendia** [comment]
I was able to replicate:

1) npm install
2) node index.js
3) Access localhost:8080


console.log returned:

> Message from server: Received request to create or join room ce3db7fc37d22
> main.js:77 Message from server: Room ce3db7fc37d22 now has 0 client(s)
> main.js:77 Message from server: Client ID cu9TUnsUDvi5mZEZAAAA created room ce3db7fc37d22
> main.js:53 Created room ce3db7fc37d22 - my client ID is cu9TUnsUDvi5mZEZAAAA
> main.js:118 Getting user media (video) ...
> main.js:48 Server IP address is: XXX

Then opened an alert:
getUserMedia() error: ReferenceError

**Comment by nitobuendia** [comment]
Error is triggered by: grabWebCamVideo
Full error: Stream error ReferenceError: streamURL is not defined

Working on it.

**Comment by nitobuendia** [comment]
Proposed #68 to fix it. //cc @samdutton 

Thank you so much @Im10Anish and @bedus-creation for your report :)
When #68 is submitted, it should work when you test it :)

**Comment by Im10Anish** [comment]
Sorry for late reply and thanks for fixing it :) (y). Once I finished my
work then I will test new changes, hope this time it working. Anyways,
thanks once again.

**Comment by samdutton** [comment]
Thank you @Im10Anish and @bedus-creation!

I've merged #68.
