### ISSUE TITLE
Change the extension of html to php

### ISSUE THREAD

**Issue by yanzai3292** [googlecodelabs/webrtc-web#71]
Is there any way to change the front-end of the WebRTC video conference HTML page into .php extension instead of .html extension?  
As i would like to connect it to the database. Thanks

**Comment by nitobuendia** [comment]
Hello @yanzai3292 

Yes and no :)

The codelab is designed to leverage node.js. By default, Node.js only supports Javascript as the backend language. This means, no php files. There are, however, ways to make PHP work on Node.js ([example](http://blog.mixu.net/2011/01/04/nginx-php-fpm-and-node-js-install-on-centos-5-5/)).

Now, WebRTC itself does not require Node.js. The reason for which we used Node.js is for signaling and allowing peers to connect to each other ([article](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/)). However, if you can replicate this signaling infrastructure in a different server, it would work and you would be allowed to do it. I have not tried, but I found [this repository](https://github.com/bndr/webRTC-php) where they try to accomplish what you want, I believe.

I hope this helps.

/cc @samdutton

**Comment by pwa** [comment]
Hi @yanzai3292 — as @nitobuendia says, this codelab is oriented to Node, but you can certainly do WebRTC from a PHP page.

**Comment by samdutton** [comment]
Hi @yanzai3292 — as @nitobuendia says, this codelab is oriented to Node, but you can certainly do WebRTC from a PHP page.
