### ISSUE TITLE
Safari reports errors on sendChannel.send(data) in step-03

### ISSUE THREAD

**Issue by jackxujh** [googlecodelabs/webrtc-web#76]
`sendChannel.send(data)` in **step-03** works just fine in Chrome. But in Safari, I always get an error. Hence the whole data exchange example does not work in Safari.

The error in Safari is:
> InvalidStateError: The object is in an invalid state.

https://github.com/googlecodelabs/webrtc-web/blob/14cadd4e2a28e9d82c35cad1c0b698bb638ac41c/step-03/js/main.js#L71

Here is a print-out of `sendChannel`: 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/24606632/39083884-b762f004-459e-11e8-952d-c84ad0d0bc06.png">

**Comment by nitobuendia** [comment]
@jackxujh Thanks a lot for reporting. I can reproduce the error as well. We would need to have a deeper look into it. I will be posting here some of the insights as I research and dig more into the issue.

**Comment by nitobuendia** [comment]
For starters, the logs in the console in Chrome and Safari are different:

**Chrome 65.0.3325.181**

```
6.736: Using SCTP based data channels
6.744: Created local peer connection object localConnection
6.745: Created send data channel
6.747: Created remote peer connection object remoteConnection
6.750: Offer from localConnection 
XXX
6.757: local ice callback
6.758: Local ICE candidate: 
XXX
6.758: AddIceCandidate success.
6.759: remote ice callback
6.760: Remote ICE candidate: 
XXX
6.760: AddIceCandidate success.
6.760: remote ice callback
6.760: local ice callback
6.763: Send channel state is: open
6.765: Receive Channel Callback
6.765: Receive channel state is: open
```

**Safari 11.1 (13605.1.33.1.2)**

```
[Log] 4.883: Using SCTP based data channels (main.js, line 185)
[Log] 4.885: Created local peer connection object localConnection (main.js, line 185)
[Log] 4.886: Created send data channel (main.js, line 185)
[Log] 4.889: Created remote peer connection object remoteConnection (main.js, line 185)
[Log] 4.895: Offer from localConnection  (main.js, line 185)
XXX
[Log] 4.897: Answer from remoteConnection  (main.js, line 185)
XXX
[Log] 5.052: local ice callback (main.js, line 185)
[Log] 5.053: remote ice callback (main.js, line 185)
```

The main difference lies on:
```
6.760: AddIceCandidate success.
6.763: Send channel state is: open
6.765: Receive Channel Callback
6.765: Receive channel state is: open
```

**Hypothesis based on that finding**
It seems that the peer are never connecting. As a result, the channel is never open and the communication cannot be executed. When pressing send, the textarea is still disabled (probably button should have been disabled too). On executing the action on a non-open channel, the code fails to execute it and throws that the channel status is not the expected one.

**Comment by nitobuendia** [comment]
I found [this thread](https://groups.google.com/forum/#!topic/discuss-webrtc/IOrsgrDaWrU) commenting the same. Applying the suggestions there works:

1. [Enable Develop](https://support.apple.com/en-sg/guide/safari/use-the-safari-develop-menu-sfri20948/mac) menu in Safari.
1. Develop > WebRTC > Disable ICE Candidate Restrictions.

After doing that, code works fine again. More on why is needed is exposed on [this article](https://webkit.org/blog/7763/a-closer-look-into-webrtc/) from WebKit (section: ICE Candidate Restrictions). @jackxujh kindly try it, this should fix your issue :)

> **ICE Candidate Restrictions**
> ICE candidates are exchanged at an early stage of a WebRTC connection to identify all possible network paths between two peers. To do this, WebKit must expose ICE candidates of each peer to websites so that they can be shared. ICE candidates expose IP addresses, and notably those that are host IP addresses can be used for tracking.
> 
> In many network topologies, however, host ICE candidates are not necessary to make the connection. Server Reflexive and TURN ICE candidates usually suffice for ensuring the connection, regardless of whether it is used for exchanging video or arbitrary data. Without access to capture devices, WebKit only exposes Server Reflexive and TURN ICE candidates, which expose IPs that could already be gathered by websites. When access is granted, WebKit will expose host ICE candidates, which maximizes the chance the connection succeeds and is efficient. We make this exception since we believe that the user is expressing a high level of trust to the website by granting access to his or her capture streams.
> 
> Some test pages may assume the availability of host ICE candidates. To test this, turn on “Disable ICE Candidate Restrictions” from the Develop > WebRTC menu, and reload the page.


// cc @samdutton This can be closed based on this information.

**Comment by samdutton** [comment]
Thanks for sleuthing @nitobuendia!
