### ISSUE TITLE
`stream` object in global scope?

### ISSUE THREAD

**Issue by kenjim83** [googlecodelabs/webrtc-web#82]
Maybe I'm missing something but on this page of the tutorial (https://codelabs.developers.google.com/codelabs/webrtc-web/#3)  it says 

```
The stream object passed to getUserMedia() is in global scope, so you can inspect it from the browser console: open the console, type stream and press Return. (To view the console in Chrome, press Ctrl-Shift-J, or Command-Option-J if you're on a Mac.)
```

however I was unable to access `stream` from the console.

**Comment by nitobuendia** [comment]
@samdutton Sent #88 to fix it.

@kenjim83 In the meantime, play around with step-02 which already have localStream and remoteStream in the global scope.
